config/routes.rb
Rails.application.routes.draw do
  root "flats#index"
  resources :flats
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/flat.rb
class Flat < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/flats_controller.rb
class FlatsController < ApplicationController

  def index
    if params[:search].present?
      @flats = Flat.where("description LIKE '%#{params[:search]}%'")
    else
      @flats = Flat.all
    end
  end

  def show
    @flat = Flat.find(params[:id])
  end
  
  def new
    @flat = Flat.new
  end

  def create
    @flat = Flat.new(flat_params)
    if @flat.save
      redirect_to @flat
    else
      render 'new'  
    end
  end

  def edit
    @flat = Flat.find(params[:id])
  end
  
  def update
    @flat = Flat.find(params[:id])
    @flat.update(flat_params)
    redirect_to flat_path(@flat)
  end

  def destroy
    @flat = Flat.find(params[:id])
    @flat.destroy
    redirect_to root_path
  end

  private

  def flat_params
    params.require(:flat).permit(:name, :address, :description, :price_per_night, :number_of_guests, :image_url)
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flats_helper.rb
module FlatsHelper
end

app/views/flats/edit.html.erb
<div class="container mt-4">
  <%# <div class="row"> %>
    <div class="col-6 m-auto">
      <h1>Edit flat</h1>
      <%= render 'shared/flat_form' %>
    </div>
  <%# </div> %>
</div>

app/views/flats/index.html.erb
<div class="container">
  <h2 class="text-center mt-3">All flats available in your area</h2>
  <div class="flat-cards d-flex justify-content-around">
    <% @flats.each do |flat| %>
            <div class="card m-3 p-1 flex-wrap">
              <div class="card-img" style="background-image: url('<%= flat.image_url %>')"></div>
              <div class="title">
                <h3><%= flat.name %></h3>
              </div>
              <div class="flat-info">
                <%= flat.address %>
                <%= flat.description %>
              </div>
              <div class="pricing mt-1">
                <p>Guests: <%= flat.number_of_guests %></p>
                <p>Price: <%= flat.price_per_night %></p>
              </div>
              <div class="card-links d-flex">
                <%= link_to "See Flat", flat_path(flat), class: "btn btn-outline-primary" %>
                <%= link_to "Delete Flat", flat_path(flat), method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-outline-danger"%>
              </div>
            </div>
    <% end %>
  </div>
</div>

app/views/flats/new.html.erb
<div class="container mt-4">
  <%# <div class="row"> %>
    <div class="col-6 m-auto">
      <h1>Add a new flat</h1>
      <%= render 'shared/flat_form' %>
    </div>
  <%# </div> %>
</div>

app/views/flats/show.html.erb
<div class="container mt-4">
  <div class="card-img" height="200" style="background-image: url('<%= @flat.image_url %>')"></div>
  <div class="col-6 m-auto">
    <h1><%= @flat.name %></h1>
    <h3><%= @flat.address %></h3>
    <h3><%= @flat.description %></h3>
    <p><%= @flat.price_per_night %></p>
    <p><%= @flat.number_of_guests %></p>
    <%= link_to 'Edit flat', edit_flat_path(@flat) %>
    <%= link_to 'Delete flat', flat_path(@flat), method: :delete, data: { confirm: "Are you sure?" } %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>coboAirbnb</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= yield %>
  </body>
</html>

app/views/shared/_flat_form.html.erb
<div class="flat-form">
    <%= simple_form_for @flat do |f| %>
    <%= f.input :name %>
    <%= f.input :address %>
    <%= f.input :description %>
    <%= f.input :price_per_night %>
    <%= f.input :number_of_guests %>
    <%= f.input :image_url %>
    <%= f.submit "Submit", disable_with: 'Submiting...' %>
    <% end  %>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to "#", class: "navbar-brand" do %>
    <%= image_tag "https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/logo.png" %>
    <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="search-bar mr-1">
        <%= form_tag(flats_path, method: :get) do %>
          <%= label_tag(:search, "Search in flats") %>
          <%= text_field_tag(:search, params[:search]) %>
          <%= submit_tag ("Search"), class: "btn btn-info" %>
        <% end %>
      </li>
      <li class="nav-item active">
        <%= link_to "Home", root_path, class: "btn btn-outline-primary mr-1" %>
      </li>
      <li>
        <%= link_to 'Add a flat', new_flat_path, class: "btn btn-outline-primary mr-1" %>
      </li>
    </ul>
  </div>
</div>